Fix compile errors
SDL is still erroring:

Sdl.gen.cs(60143,45): Error CS0266 : Cannot implicitly convert type 'long' to 'nint'. An explicit conversion exists (are you missing a cast?)
Sdl.gen.cs(60143,35): Error CS0133 : The expression being assigned to 'Sdl.MaxSint64' must be constant

[NativeTypeName("#define SDL_MAX_SINT64 SDL_SINT64_C(0x7FFFFFFFFFFFFFFF)")]
public const nint MaxSint64 = unchecked(0x7FFFFFFFFFFFFFFF);

At first glance, this might be a ClangSharp issue with how these defines are generated on Linux.